### ISSUE TITLE
Setting up Twitter search engine using Twitter API and Algolia

### ISSUE THREAD

**Issue by kavuong** [bitprj/gatsby-bitcamp#3]
Will correspond to week 3 of BitCamp

- [x] Using gatsby-source-twitter to obtain Twitter data from the search/tweets endpoint
- [x] Running GraphQL queries in Postman to see Twitter data in Algolia
  - [x] Setup with Postman Runners, to avoid repetition
- [x] Making Algolia data searchable (to finalize the search engine and make the search bar)

**Deadline**
Thurs, 4/2
(added last check - now Fri, 4/3)

**Comment by jeffchhen** [comment]
Finished Making Aloglia searching

**Comment by jeffchhen** [comment]
The backend with twitter tweets is all set up.
