### ISSUE TITLE
Get Jeff's Site up and running locally

### ISSUE THREAD

**Issue by kavuong** [bitprj/gatsby-bitcamp#4]
- [x] Install Gatsby
- [x] Deploy to Netlify

**Deadline**
Fri, 4/3

**Comment by jeffchhen** [comment]
https://affectionate-johnson-10122b.netlify.com/

**Comment by kavuong** [comment]
> <https://affectionate-johnson-10122b.netlify.com>
<sub>[View in Slack](https://bitdarlene.slack.com/archives/G011941QN1K/p1585896340019700)</sub>
